"use strict";

/**
 * Careers view react-component, which gets rendered after the router invokes "reply.reactview("careers");"
 *
 * <i>Copyright (c) 2015 ezHome - http://ezhome.com</i><br>
 * Proprietary License
 *
 *
 * @module views/careers.jsx
 * @class ViewCareers
 * @since 2.0.0
*/

import "../assets/css/base.scss";
import "../assets/css/pages/careers.scss";

import React, {PropTypes} from "react";
import TitleHeader from "../modules/title-header.jsx";
import ContentCareers from "../modules/careers/content-careers.jsx";
import Footer from "../react-components/footer.jsx";

const ViewCareers = React.createClass({

    propTypes: {
        /**
         * The Component its children, which basicly consist of one react-component: the view.
         *
         * @property children
         * @type Object
         * @since 2.0.0
        */
        children: PropTypes.object,

        /**
         * ezhome's urls's to facebook, twitter etc.
         *
         * @property ezhomeURLs
         *    @property {String} ezhomeURLs.facebook link to ezhome's facebook-page
         *    @property {String} ezhomeURLs.twitter link to ezhome's twitter-page
         *    @property {String} ezhomeURLs.instagram link to ezhome's instagram-page
         *    @property {String} ezhomeURLs.pinterest link to ezhome's pinterest-page
         * @type Number
         * @since 2.0.5
        */
        ezhomeURLs: PropTypes.object.isRequired,

        /**
         * The title for the page
         *
         * @property titleHeader
         * @type String
         * @since 2.0.0
        */
        titleHeader: PropTypes.string,

        /**
         * The sub-title for the page
         *
         * @property titleSubHeader
         * @type String
         * @since 2.0.0
        */
        titleSubHeader: PropTypes.string,

        /**
         * All ezHome"s open positions that are currently defined at Workable.
         * See www.workable.com
         *
         * @property workableData
         * @type Array
         * @since 2.0.0
        */
        workableData: PropTypes.array.isRequired
    },

    /**
     * React render-method --> renderes the Component.
     *
     * @method render
     * @return ReactComponents
     * @since 2.0.0
     */
    render() {
        const props = this.props; // for optimization uglifyJS

        return (
            <div className="container-fluid ezh-no-padding ezh-careers-container">
                <div>
                    <TitleHeader
                        titleHeader={props.titleHeader}
                        titleSubHeader={props.titleSubHeader} />
                    <ContentCareers workableData={props.workableData} />
                    <Footer
                        ezhomeURLs={props.ezhomeURLs}
                        lightFooter={true} />
                </div>
            </div>
        );
    }

});

export default ViewCareers;

// Below is he API for the protected this.props properties:

/**
 * The String where the assets of this specific version are.
 * Typically like: `/assets/0.0.1/`
 * Use this if you want the url to the assets with a dynamically version-number
 * that matches the production-version
 *
 * @property __assetsdir
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * meta char-set
 *
 * @property __charset
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * meta description
 *
 * @property __description
 * @protected
 * @private
 * @type String
 * @since 2.0.0
*/

/**
 * The device that the visitor is using: "desktop", "tablet" or "mobile"
 *
 * @property __device
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * Google-analytics api-key
 *
 * @property __ga
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * Url for the shared script-file. This files is generated by webpack as common-script,
 * and also holds all webpack-functionality which runs on the client.
 *
 * @property __itsacommonscript
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The bundled inline css content: bundled for this specific pageview only
 *
 * @property __itsapageinlinecss
 * @type Object
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * Url for the bundled css: bundled for this specific pageview only
 *
 * @property __itsapagelinkcss
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * Url for the page(view)-specific script-file. This files is generated by webpack as a chunck-file.
 *
 * @property __itsapagescript
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The language to be used for this page. Is being controlled by the visitor,
 * either by its lang-preferences, or whenever the visitor changes to another
 * language through the web-application (f.e. "en").
 *
 * @property __lang
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The language-prefix that currently is in the url, whenever u user
 * manually switched to another language (f.e. "/fr").
 *
 * @property __langprefix
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * An hash with all available languages for this web-application.
 * F.e. {"en": "default, "fr": true, "nl": true}
 *
 * @property __languages
 * @type Object
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The locales on the client
 *
 * @property __locales
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The active url-pathname
 *
 * @property __path
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * Active routes (from /routes.js) that can be used for client-side rendering
 *
 * @property __routes
 * @type Array
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The time that sessions may be kept in localstorage
 *
 * @property __sessiontime
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The title for the page
 *
 * @property __title
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The active uri
 *
 * @property __uri
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * Full useragent-information
 *
 * @property __useragent
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The version of the web-application
 *
 * @property __version
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * The name of the page"s view
 *
 * @property __view
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/

/**
 * meta viewport
 *
 * @property __viewport
 * @type String
 * @protected
 * @private
 * @since 2.0.0
*/
